### ISSUE TITLE
Preserve / Count up attribute?

### ISSUE THREAD

**Issue by manavortex** [grosser/ar_merge#2]
Hey, 

this gem almost fits my needs perfectly. The only problem is that I am losing the quantities.

Is there any way - or can you hack in any way for me - to preserve one attribute in the combined record? As in, add it up or so? Or maybe let me map into the merge so I'm more flexible?

Can I compare on multiple columns, maybe?

Thanks!

**Comment by grosser** [comment]
- make a PR to add a block to `merge!` that then yields both records ... then custom logic can live there
 - override `def merge!` and change the other/self as you desire before calling `super`

**Comment by manavortex** [comment]
Hey, 

thanks for your quick reply. I will try!

regards
